/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package versionFinal.frontEnd;



/**
 *
 * @author Agustín Toya
 */
public class VentanaLectores extends javax.swing.JPanel {

    private ControladorCliente ctrl;
    
    /**
     * Creates new form VentanaLectores
     */
    public VentanaLectores(ControladorCliente controlador) {
        this.ctrl = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenido = new javax.swing.JTextPane();
        volver = new javax.swing.JButton();

        encabezado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado.setText("Contenido del archivo");

        contenido.setEditable(false);
        jScrollPane1.setViewportView(contenido);

        volver.setBackground(new java.awt.Color(208, 0, 82));
        volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 0, 0));
        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                volverKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(encabezado)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(encabezado)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(volver)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void volverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_volverKeyPressed
        // TODO add your handling code here:
        ctrl.volverMenu();
    }//GEN-LAST:event_volverKeyPressed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        ctrl.volverMenu();
    }//GEN-LAST:event_volverMouseClicked

    public void setTitulo(String nombreArchivo){
        encabezado.setText("Contenido del archivo \"" +  nombreArchivo + "\"");
    }
    
    public void setTextoMostrar(String texto){
        contenido.setText(texto);
    }
    
     public void abrirConfirmacion(String texto){
        ConfirmacionAccion confAct = new ConfirmacionAccion(ctrl.getPrincipal(), true, ctrl);
        confAct.setMensaje(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane contenido;
    private javax.swing.JLabel encabezado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
