/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package v2;

import java.awt.Color;
import java.awt.SystemColor;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Agustín Toya
 */
public class InicioSesion extends javax.swing.JPanel {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();

        defaultUserBorder = passwordField.getBorder();
        defaultPassBorder = ingresarUsuario.getBorder();
        mensajeErrorUsuario.setText("");
        mensajeErrorContraseña.setText("");
        ingresarUsuario.select(0, 0);
        ingresarUsuario.setCaretPosition(ingresarUsuario.getText().length());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        ingresarUsuario = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        verContraseña = new javax.swing.JButton();
        labelIngresarUsuario = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        mensajeErrorUsuario = new javax.swing.JLabel();
        mensajeErrorContraseña = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Iniciar sesión");

        ingresar.setBackground(new java.awt.Color(78, 200, 82));
        ingresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ingresar.setForeground(new java.awt.Color(0, 0, 0));
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(208, 80, 82));
        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 0, 0));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        ingresarUsuario.setForeground(new java.awt.Color(100, 100, 100));
        ingresarUsuario.setText("pepeBustillo");
        ingresarUsuario.setNextFocusableComponent(passwordField);
        ingresarUsuario.setSelectionEnd(0);
        ingresarUsuario.setSelectionStart(0);
        ingresarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarUsuarioMouseClicked(evt);
            }
        });
        ingresarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingresarUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresarUsuarioKeyReleased(evt);
            }
        });

        passwordField.setText("HolaMundo2023");
        passwordField.setNextFocusableComponent(verContraseña);
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });

        verContraseña.setBackground(new java.awt.Color(200, 200, 202));
        verContraseña.setForeground(new java.awt.Color(0, 0, 0));
        verContraseña.setText("Ver");
        verContraseña.setInheritsPopupMenu(true);
        verContraseña.setNextFocusableComponent(cancelar);
        verContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verContraseñaMouseClicked(evt);
            }
        });

        labelIngresarUsuario.setLabelFor(ingresarUsuario);
        labelIngresarUsuario.setText("Usuario");

        labelContraseña.setLabelFor(passwordField);
        labelContraseña.setText("Contraseña");

        mensajeErrorUsuario.setForeground(new java.awt.Color(200, 0, 0));
        mensajeErrorUsuario.setLabelFor(ingresarUsuario);
        mensajeErrorUsuario.setText("--");

        mensajeErrorContraseña.setForeground(new java.awt.Color(200, 0, 0));
        mensajeErrorContraseña.setLabelFor(passwordField);
        mensajeErrorContraseña.setText("--");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(ingresar)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addComponent(labelIngresarUsuario)
                    .addComponent(ingresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verContraseña))
                    .addComponent(mensajeErrorUsuario)
                    .addComponent(labelContraseña)
                    .addComponent(mensajeErrorContraseña))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(labelIngresarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeErrorUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(labelContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensajeErrorContraseña)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresar)
                    .addComponent(cancelar))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:

        // Llamos a ingresar para que se encargue

    }//GEN-LAST:event_ingresarActionPerformed

    public void ingresar() {
        String contraseña = new String(passwordField.getPassword());
        String nombreUsuario = ingresarUsuario.getText();

        if (contraseña.length() == 0 && nombreUsuario.length() == 0) {
            mensajeErrorUsuario.setText("El campo usuario no puede estar vacío");
            mensajeErrorContraseña.setText("El campo contraseña no puede estar vacío");
            ingresarUsuario.setBorder(errorBorder);
            passwordField.setBorder(errorBorder);

        } else {
            boolean userValido = Funciones.validarUsuario(nombreUsuario);
            boolean datosValidos = false;
            if (!userValido) {
                
                mensajeErrorUsuario.setText("Usario invalido, no existe en el sistema");
                Border borde = new LineBorder(SystemColor.red);
                ingresarUsuario.setBorder(borde);
            } else {
                datosValidos = Funciones.validarDatos(nombreUsuario, contraseña);
            }

            if (userValido && !datosValidos) {
                mensajeErrorContraseña.setText("La contraseña no es correcta");
                Border borde = new LineBorder(SystemColor.red);
                passwordField.setBorder(borde);
            }

            if (userValido && datosValidos) {
                Funciones.irMenu();
            }
        }

    }

    // Este incluye el click sobre el componente y el enter si estas parado sobre el, me sirve más
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        Funciones.principal.cerrar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        // TODO add your handling code here:
        passwordField.setText("");
        passwordField.setForeground(Color.BLACK);
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void ingresarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarUsuarioMouseClicked
        // TODO add your handling code here:
        ingresarUsuario.setForeground(Color.BLACK);
        mensajeErrorUsuario.setText("");
        ingresarUsuario.setBorder(defaultUserBorder);
    }//GEN-LAST:event_ingresarUsuarioMouseClicked

    private void verContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContraseñaMouseClicked
        // TODO add your handling code here:
        if (!contraseñaExpuesta) {
            contraseñaExpuesta = true;
            passwordField.setEchoChar((char) 0);
            verContraseña.setText("Ocultar");
        } else {
            verContraseña.setText("Ver");
            contraseñaExpuesta = false;
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_verContraseñaMouseClicked

    private void ingresarUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresarUsuarioKeyPressed
        // TODO add your handling code here:
        if (!yaEscribioUser) {
            ingresarUsuario.setText("");
            ingresarUsuario.setForeground(Color.BLACK);
            mensajeErrorUsuario.setText("");
            yaEscribioUser = true;
        }

        ingresarUsuario.setBorder(defaultUserBorder);
    }//GEN-LAST:event_ingresarUsuarioKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:
        if (!yaEscribioPass) {
            passwordField.setText("");
            passwordField.setForeground(Color.BLACK);
            mensajeErrorUsuario.setText("");
            yaEscribioPass = true;
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void ingresarUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresarUsuarioKeyReleased
        // TODO add your handling code here:
         if (evt.getExtendedKeyCode()==KeyEvent.VK_ENTER) ingresar();
    }//GEN-LAST:event_ingresarUsuarioKeyReleased

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        // TODO add your handling code here:
         if (evt.getExtendedKeyCode()==KeyEvent.VK_ENTER) ingresar();
    }//GEN-LAST:event_passwordFieldKeyReleased

    private boolean contraseñaExpuesta = false;
    private boolean yaEscribioUser = false;
    private boolean yaEscribioPass = false;

    private Border defaultUserBorder;
    private Border defaultPassBorder;
    private Border errorBorder = new LineBorder(SystemColor.red, 2);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton ingresar;
    private javax.swing.JTextField ingresarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelIngresarUsuario;
    private javax.swing.JLabel mensajeErrorContraseña;
    private javax.swing.JLabel mensajeErrorUsuario;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton verContraseña;
    // End of variables declaration//GEN-END:variables
}
