/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package v2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Agustín Toya
 */
public class Principal extends javax.swing.JFrame  {

    /**
     * Creates new form Principal
     */
    Menu menu = new Menu();
    VentanaEscritor vE = new VentanaEscritor();
    VentanaLector vL = new VentanaLector();
    InicioSesion login = new InicioSesion();

    public Principal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.
        
        jPanel1.setVisible(false);
        contenedor.add(login);

        //contenedor.add(vE);
        //vE.setEnabled(false);
        //vE.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        contenedor.add(jPanel1);

        getContentPane().add(contenedor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Funciones.principal.setVisible(true);
            }
        });
    }
    
    public static void cerrar(){
        System.exit(0);
    }
    public  void volverMenu(){
        contenedor.add(menu);
        menu.setVisible(true);
        //vE.setVisible(false);
        jPanel1.setVisible(false);
        contenedor.validate();
    }
    
    public void irMenu(){
        contenedor.remove(login);
        contenedor.add(menu);
        menu.setVisible(true);
        menu.setEnabled(true);
        login.setEnabled(false);
        login.setVisible(false);
        contenedor.validate();
    }
    
   public void irVentanaEscritores(){
        contenedor.add(vE);
        vE.setVisible(true);
        vE.setEnabled(true);
        menu.setEnabled(false);
        menu.setVisible(false);
        contenedor.validate();
    } 
   
    public void irVentanaLectores(){
        contenedor.add(vL);
        vL.setVisible(true);
        vL.setEnabled(true);
        menu.setEnabled(false);
        menu.setVisible(false);
        contenedor.validate();
    }
    
    public void irInicioSesion(){
        // Por ahora vacía, no se si es necesaria
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
